SELECT COUNT(*) FROM EMPLOYEES WHERE DEPARTMENT_ID = 90;
SELECT COUNT(*) FROM EMPLOYEES WHERE DEPARTMENT_ID = 30;

SELECT DEPARTMENT_ID, COUNT(*) FROM EMPLOYEES 
   group by DEPARTMENT_ID;

SELECT DEPARTMENT_ID,MAX(SALARY),MIN(SALARY),SUM(SALARY),AVG(SALARY) FROM EMPLOYEES 
   group by DEPARTMENT_ID;
    
SELECT JOB_ID FROM EMPLOYEES group by JOB_ID;

-- 직원 테이블 LAST_NAME을 중복 제거하고 조회
SELECT distinct LAST_NAME FROM EMPLOYEES;

-- 직원 테이블 LAST_NAME 그룹별로 인원수 조회
SELECT LAST_NAME, COUNT(*) FROM EMPLOYEES group by LAST_NAME;

-- LAST_NAME 그룹의 카운트가 2이상인 행들만 조회
select LAST_NAME ,COUNT(*) FROM EMPLOYEES 
group by LAST_NAME
having COUNT(*) >1;

-- 위의 성을 가지는 직원 목록 조회
SELECT * FROM EMPLOYEES WHERE LAST_NAME IN(
select LAST_NAME
FROM EMPLOYEES 
group by LAST_NAME
having COUNT(*) >1
);
SELECT * FROM EMPLOYEES WHERE SALARY =(
select distinct SALARY  FROM EMPLOYEES ORDER BY SALARY LIMIT 1 OFFSET 4);

-- 상위 연봉 50명에 대해서 부서별로 몇명이 있는지
SELECT DEPARTMENT_ID, COUNT(*) FROM (
SELECT  * FROM EMPLOYEES ORDER BY SALARY DESC,FIRST_NAME ASC LIMIT 50)AS A
GROUP BY DEPARTMENT_ID;

USE HR;